import { useParams, Link } from 'react-router-dom';
import { useEffect, useState } from 'react';
import { AlertTriangle } from 'lucide-react';
import type { FindingsResponse, FindingSchema } from '../types/api';
import { getFindings } from '../api/client';
import { Panel } from '../components/Panel';
import { FindingCard } from '../components/FindingCard';
import { EmptyState } from '../components/EmptyState';
import { ErrorState } from '../components/ErrorState';
import { StatusBadge } from '../components/StatusBadge';
import { CATEGORY_LABELS } from '../lib/format';

export function Findings() {
  const { id } = useParams<{ id: string }>();
  const [data, setData] = useState<FindingsResponse | null>(null);
  const [error, setError] = useState<{ message: string; isNetwork: boolean } | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!id) { setLoading(false); return; }
    getFindings(id)
      .then((r) => { setData(r); setLoading(false); })
      .catch((err) => { setError({ message: err.message, isNetwork: err.name === 'NetworkError' }); setLoading(false); });
  }, [id]);

  if (!id) {
    return (
      <div className="max-w-3xl mx-auto px-6 py-8">
        <Panel>
          <EmptyState
            title="No assessment selected"
            description="Run an assessment first, then navigate here from the result page."
            action={<Link to="/new" className="text-xs text-[var(--accent)] hover:underline">New Assessment →</Link>}
          />
        </Panel>
      </div>
    );
  }

  // Group findings by category
  const grouped = data?.findings.reduce<Record<string, FindingSchema[]>>((acc, f) => {
    (acc[f.category] ??= []).push(f);
    return acc;
  }, {}) ?? {};

  return (
    <div className="max-w-3xl mx-auto px-6 py-8 space-y-5">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-xl font-bold text-[var(--text-primary)] tracking-tight">Findings</h1>
          <p className="mt-0.5 text-xs text-[var(--text-muted)] font-mono">{id}</p>
        </div>
        {data && (
          <span className="text-sm font-semibold text-[var(--text-primary)]">
            {data.count} finding{data.count !== 1 ? 's' : ''}
          </span>
        )}
      </div>

      {loading && (
        <div className="space-y-3 animate-pulse">
          {[1, 2, 3].map((i) => <div key={i} className="h-16 rounded-lg bg-[var(--surface-2)]" />)}
        </div>
      )}

      {error && !loading && (
        <Panel>
          <ErrorState message={error.message} isNetwork={error.isNetwork} onRetry={() => window.location.reload()} />
        </Panel>
      )}

      {!loading && !error && data && (
        <>
          {data.count === 0 ? (
            <Panel>
              <EmptyState
                icon={<AlertTriangle className="w-8 h-8" />}
                title="No integrity concerns identified"
                description="No findings were generated by the executed detectors. Note: this does not guarantee safety if coverage is incomplete."
              />
            </Panel>
          ) : (
            Object.entries(grouped).map(([category, findings]) => (
              <Panel
                key={category}
                title={CATEGORY_LABELS[category] ?? category}
                actions={<StatusBadge value={category} variant="category" />}
              >
                <div className="space-y-2">
                  {findings.map((f) => (
                    <FindingCard key={f.finding_id} finding={f} />
                  ))}
                </div>
              </Panel>
            ))
          )}

          <div className="text-xs text-[var(--text-muted)] px-1">
            <Link to={`/assessments/${id}/result`} className="text-[var(--accent)] hover:underline">
              ← Back to assessment result
            </Link>
          </div>
        </>
      )}
    </div>
  );
}
